[package]
name = "sassy"
version = "0.1.0"
edition = "2024"

[profile.release]
incremental = true
opt-level = 3
debug = true

[dependencies]
arrayvec = "0.7.6"
criterion = "0.5.1"
rand = "0.9.0"
pa-types.git = "https://github.com/pairwise-alignment/pa-types"
clap = { version = "4.5.37", features = ["derive"] }
needletail = "0.6.3"

[[bench]]
name = "bench"
harness = false
