[package]
name = "sassy"
version = "0.1.0"
edition = "2024"

[profile.release]
incremental = true
opt-level = 3
debug = true

[dependencies]
arrayvec = "0.7.6"
criterion = "0.5.1"
rand = "0.9.0"
pa-types.git = "https://github.com/pairwise-alignment/pa-types"
clap = { version = "4.5.37", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
num_cpus = "1.16.0"
needletail = "0.6.3"

[[bench]]
name = "bench"
harness = false

[dev-dependencies]
edlib_rs = { git = "https://github.com/rickbeeloo/edlib-rs-cli.git" }
toml = "0.7"
serde = { version = "1.0", features = ["derive"] }

[[example]]
name = "bench"
path = "examples/bench.rs"