query_lengths = [40, 80, 100, 200, 400, 800, 1000, 1200, 1400, 1600, 1800, 2000]
text_lengths = [1000, 2000, 5000, 10000, 20000,100000]
output_file = "examples/bench_unbounded.tsv"
edlib_k = 1
sassy_k = 1
match_fraction = 0.001
max_edits = 1
bench_iter = 50
alphabet = "dna"
profile = "iupac"
rc = "withoutrc"
bound = "bounded"