query_lengths   = [20, 40, 80, 100, 200, 500, 1000]
text_lengths    = [1000, 2000, 5000, 10_000, 20_000, 50_000, 100_000, 200_000]
k               = [1]
match_fraction  = [1]
bench_iter      = [200]
alphabet        = ["dna"]
profile         = ["dna"]
rc              = ["withoutrc"]
verbose         = false
edlib = true
