query_lengths   = [20, 40, 80, 100, 150, 200, 250, 300, 1000]
text_lengths    = [1000, 2000, 5000, 10_000, 50_000, 100_000, 1_000_000]
k               = [1, 2, 3, 4, 5]
match_fraction  = [0.001]
bench_iter      = [200]
alphabet        = ["dna"]
profile         = ["dna", "iupac"]
rc              = ["withoutrc"]